### ISSUE TITLE
Visual Studio Errors

### ISSUE THREAD

**Issue by jpveldtman** [LokeshPatel/Cordova-Plugin-FCMNotification#1]
Getting a bunch of errors when adding this on Visual Studio, please help

**Comment by LokeshPatel** [comment]
Hi,
Can send me your error ?
Better for me to understand your problem.
Thanks,

**Comment by LokeshPatel** [comment]
Hi,
Visual studio not support yet !!!!
Thanks,
Lokesh Patel
