### ISSUE TITLE
TypeError: navigator.FCMNotification is undefined

### ISSUE THREAD

**Issue by olusegun171** [LokeshPatel/Cordova-Plugin-FCMNotification#3]
I am trying to set up a push notification on ionic project for Android but i got this error whenever i run the project.

TypeError: navigator.FCMNotification is undefined, http://localhost:8101/js/app.js, Line: 15

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.6
Ionic App Lib Version: 0.6.2
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04.1 LTS 
Node Version: v4.2.6

**Comment by jokorivai** [comment]
You nee to run your code on android device (either emulator or android phone)

**Comment by LokeshPatel** [comment]
Yes,Run plugin in both emulator and device.
Please try running sample code.
https://www.dropbox.com/s/ljizdh9ue3yb0fu/sampleapp_.zip?dl=0

In this sample code need to change.
Google service js file and package name : com.sampleapp

Thanks,
Lokesh Patel
